### ISSUE TITLE
Question: Is This Normal Behaviour For Binding Requests?

### ISSUE THREAD

**Issue by DoomT-DaveK** [mycrl/turn-rs#114]
Hi there.

A little background: I'm integrating Valve's [GameNetworkingSockets](https://github.com/ValveSoftware/GameNetworkingSockets) into our game for [Peer-To-Peer](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/README_P2P.md#requirements) networking. One of the requirements is to have a TURN server and that is how I came across this project. In our game, players connect to our server and then create a lobby and then up to 3 other players can join for online co-op.

I would like to know if this is normal behaviour related to Binding Requests. I'm seeing a LOT of logs related to the binding request. These seem to be coming from the host player, once client player joins the lobby and connects to the host. I made the client player disconnect from the host player and leave the lobby and after a few seconds the logs stopped. I did the same thing (client player disconnected from host) and then on the host player I closed the lobby and the logs immediately stopped. I wanted to see if it was going to do this forever, so I just let it go and after about 2 minutes it stopped. It seems to be happening around 20 times per second (give or take). Here is a small sample of the logs over 1 second:
```
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.202Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.254Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.305Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.354Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.408Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.457Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.503Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.557Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.612Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.658Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.714Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.757Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.807Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.861Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.915Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
Dec 04 19:34:24 [HOSTNAME] turn-server[24966]: 2024-12-04T19:34:24.961Z INFO  [turn_server::observer] binding: addr=[IP_ADDRESS]:52292
```

I would have thought there would have only been 1 log line for it. So, is this normal behaviour? I tried the Trickle-ICE web tool and with the server and it only logged it once.

Reading through the source code for GameNetworkingSockets, they do [implement the most important subset](https://github.com/ValveSoftware/GameNetworkingSockets/blob/master/src/steamnetworkingsockets/clientlib/steamnetworkingsockets_stun.cpp#L3) of RFC8489. So I'm leaning towards something might not be correct in their implementation. Chances are I'll need to make an Issue on their repo about this, but wanted to double check here first to see if this behaviour is correct or not.

Thanks in advance.

**Comment by mycrl** [comment]
No need to panic, it's perfectly normal.
It's normal to send duplicate STUN binding requests, it's very common in some webrtc implementations, most come from the ice negotiation phase of rtc, and the turn server has very low overhead in the face of STUN binding requests (most of the overhead comes from notifying the external service when the request occurs) so there's no need to worry about it.

**Comment by DoomT-DaveK** [comment]
Thanks for the quick reply.

If this is normal/expected behaviour I'll close this issue. It just seemed weird to me that there would be that many binding requests for that long of time and just wanted to confirm. 

I'll close this issue.
