### ISSUE TITLE
Any Kubernetes updates coming soon?

### ISSUE THREAD

**Issue by anishmenon** [mycrl/turn-rs#58]
As the turn is too important for video communication systems like Jitsi , BBB
I'm using coturn on docker also tried a Stunner recently

none of them has a proper solution for deploying the turn service on K8s 
via FQDN and tls 443 ( cert-manager) support.

It will be great if this rust-based turn project can be deployed with those requirements. 

#kubernetes #cert-manager #turn #coturn

**Comment by mycrl** [comment]
> As the turn is too important for video communication systems like Jitsi , BBB I'm using coturn on docker also tried a Stunner recently
> 
> none of them has a proper solution for deploying the turn service on K8s via FQDN and tls 443 ( cert-manager) support.
> 
> It will be great if this rust-based turn project can be deployed with those requirements.
> 
> #kubernetes #cert-manager #turn #coturn

I don't know much about k8s, if you are interested, I can help you add k8s support.
At present, this project is only suitable for single-point deployment. Of course, you can deploy multiple turn servers, but you need to handle how to assign a certain user to a certain turn.
However, I am currently adding support for turn clusters, which can be composed of multiple turn servers (nodes) and a turn routing to form a cluster, but this has nothing to do with k8s.
As for FQDN, I don't understand your request. What do you want the turn server to do? Where is the FQDN in the turn server?
