### ISSUE TITLE
NixOS Support

### ISSUE THREAD

**Issue by nyabinary** [mycrl/turn-rs#94]
NixOS support would be nice :3

**Comment by mycrl** [comment]
I don't have a nixos environment at hand. If your OS supports installing the rust toolchain, you can try to compile one by yourself. My project currently does not seem to have any dependencies that would prevent cross-platform use. The build products in releases are automatically built by github actions and do not statically link libc, so if the build products in releases cannot run in your environment, you can try to compile one. You only need to "cargo build --release", and the rest will be automatically completed by the rust toolchain.

**Comment by mycrl** [comment]
@Bot-wxt1221 Okay, I've pushed Cargo.lock to the main branch.

**Comment by mycrl** [comment]
@Bot-wxt1221 I released a small version

https://github.com/mycrl/turn-rs/releases/tag/v3.0.1

**Comment by nyabinary** [comment]
https://github.com/NixOS/nixpkgs/pull/338928 has been merged.

**Comment by mycrl** [comment]
> [NixOS/nixpkgs#338928](https://github.com/NixOS/nixpkgs/pull/338928) has been merged.

@nyabinary How to install turn-rs in nixos, I don't know how to use nixos, but I want to add the nixos installation method to the README, can you give me some help?
